# action.yml
name: PNX Patchy
description: Run
inputs:
  env:
    description: The environment
    required: true

runs:
  using: composite
  steps:
    - id: skpr-deploy
      shell: bash
      run: skpr mysql image pull ${{ inputs.env }}
